### ISSUE TITLE
"Polling has not run yet." with matching emails after "Test Connection"

### ISSUE THREAD

**Issue by kraftydevil** [jenkinsci/poll-mailbox-trigger-plugin#9] opened 2016-03-14 15:04 UTC
Jenkins: 1.641
Plugin: 1.021

The plugin hasn't been triggering any builds of late, and is on a "once a minute" poll cycle.

When I use the "Test Connection" button, it finds matching emails just fine.

But when I check the "Poll Mailbox Trigger Log" it says that "Polling has not run yet."

What could be going on and how can I further investigate this issue?

**Comment by nickgrealy** [comment] 2016-03-14 21:31
Hi, I think I've [seen this before](https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-29234), a restart should fix it. 

Quick question before you go though, when did the issue start occurring? Did you recently upgrade the plugin?

Thanks,  Nick

**Comment by kraftydevil** [comment] 2016-03-14 22:04
Thanks - I did recently upgrade - however, the issue existed before I upgraded. I believe I upgraded from 1.019.

I added the loggers and restarted Jenkins. It appears to be working fine, although I'm sure I restarted when upgrading the plugin so maybe adding the loggers is what did it.

If the functionality dies again I'll let you know

**Comment by nickgrealy** [comment] 2016-03-14 22:13
Cool, thanks for the feedback. I don't know the root cause but I suspect it's the upgrade process (we actually use another plugin (xtrigger) for the polling behaviour).

Will try to reproduce the problem, and in the meantime, see if I can "force a restart" for future updates.

I'm going to leave this ticket open, to work on a proper solution. Tactical workaround is to restart Jenkins.

**Comment by kraftydevil** [comment] 2016-03-18 16:07
Restarting Jenkins does the trick - but at some point it stops polling. I can't tell when or why.

Just to be clear, the problem did not occur when I upgraded the plugin itself. It may have occurred when upgrading Jenkins, however. 

Here's the sequence of events:
1. Upgraded Jenkins instance
2. Then there was some period of time where status of the plugin was unknown. In other words I'm not sure if the Jenkins upgrade caused it or not. I'm not sure if it worked for a some after the Jenkins upgrade or not.
3. Noticed the plugin was not polling
4. Upgraded the plugin
5. Still doesn't poll unless I restart Jenkins - but only polls for an unknown amount of time

**Comment by nickgrealy** [comment] 2016-04-05 14:16
I've just released version 1.022 (available in the next 24 hours). Can you please update to 1.022 (at your leisure) and see if this issue is reproducible?

**Comment by kraftydevil** [comment] 2016-04-05 16:28
Will do.

**Comment by nickgrealy** [comment] 2016-04-13 13:21
How'd it go?

**Comment by kraftydevil** [comment] 2016-04-13 16:37
Hadn't upgraded yet - upgrading now and will test.

**Comment by kraftydevil** [comment] 2016-04-13 22:24
Ok it's definitely working. I will keep an eye on it.

**Comment by nickgrealy** [comment] 2016-04-14 13:27
Great to hear!

**Comment by nickgrealy** [comment] 2016-04-23 01:00
@kraftydevil - what do you reckon? Can we close this ticket (not able to reproduce), and re-open it if someone else has the same issue?

**Comment by kraftydevil** [comment] 2016-04-23 01:05
I reckon we should close this ticket :-) I'll let you know if I see this
again.

**Comment by nickgrealy** [comment] 2016-04-25 22:25
@kraftydevil excellent, thanks.

**Closed as completed by nickgrealy** 2016-04-25 22:25 UTC
Labels: Bug

**Comment by smacnak** [comment] 2017-10-09 19:36
I've been getting the same error and I've restarted 100 times. Was there any resolution on the cause of the problem?

**Comment by nickgrealy** [comment] 2017-10-23 06:05
Hi @smacnak,

No, we didn't get the root cause, and I wasn't able to reproduce the issue.

If you can provide any insights (e.g. logs with a stacktrace), that would be much appreciated!

(Also https://github.com/jenkinsci/poll-mailbox-trigger-plugin/blob/master/.github/ISSUE_TEMPLATE.md)

Kind regards,
Nick

**Comment by smacnak** [comment] 2017-10-30 16:37
Ok because I seem to get this problem once or twice a week where when I click on the "Poll Mailbox Trigger Log" button in my job it lingers at "Polling has not run yet."

This seems to happen after I have ran so many jobs and eventually it just starts to work again, which makes me wonder if there is some sort of memory problem going on. I have looked into the temp directory in Windows where copies of all the attachments are downloaded from this plugin and they accumulate rather quickly.

Doing a restart or a safe restart don't cause the polling to immediately run again either, it just takes a like an hour or so and then it starts to run them again on its own.

I don't have a log of this since when I attempt to place a logger on this plugin, it first doesn't recognize "org.jenkinsci.plugins.pollmailboxtrigger" as a package, but I use it anyways, and secondly it just doesn't generate any log report (probably because of the first problem).

**Comment by smacnak** [comment] 2017-10-30 18:19
After investigating this problem some more, I see that the last attachment that is downloaded from the job (as specified by the Poll Mailbox Trigger - Attachments: Download to a time stamped directory) is unable to be opened. Attempting to open the attachment in Adobe results in the following error:

"There was an error opening this document. The file is damaged and could not be repaired"

But when I look at all other successful builds, I can open the attachments.

Could corrupted attchments cause the Poll Mailbox Trigger to get held up to where it would stay at "Polling has not run yet" as the status?

**Comment by smacnak** [comment] 2017-10-30 20:59
Further investigating: the downloaded attachment wasn't corrupted, it was such a big file that it takes Jenkins a long time to download it. Polling doesn't continue until after the whole file has been downloaded.

**Comment by nickgrealy** [comment] 2017-10-31 02:44
Hi @smacnak ,
That's some fantastic investigation! What would be the ideal behaviour in these circumstances?

I'm reviewing the code, here's some of my own notes on the current behaviour:

**Notes: (not entirely relevant)**

- attachments aren't download for "test connection"
- attachments are downloaded synchronously (i.e. one after the other)
- an email isn't marked as read, until all attachments have downloaded (if option is enabled)

**Questions:**

- does the polling run a second time, if the previous polling is still "in flight"? (i.e. big download)
- If yes, does it pickup the same email and re-try to download?

We could make [this snippet asynchronous...](https://github.com/jenkinsci/poll-mailbox-trigger-plugin/blob/master/src/main/groovy/org/jenkinsci/plugins/pollmailboxtrigger/PollMailboxTrigger.java#L297-L318) but we'd have to mark the email as "read" up front (and revert on failure?).

**Comment by smacnak** [comment] 2017-10-31 17:16
I feel like ideal behavior would be to start the build time or have a message instead of "Polling has not yet run." I agree with your notes as well, they seem to agree with what I've seen.

As far as I can tell, polling does not run again until the "big download" is finished. The "big downloads" I'm working with, on occasion, are around 19 MB.
